Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Models/Autenticacion.cs
namespace Doble_Autenticacion_NET.Models
{
    public class Autenticacion
    {
        public string tipoAutenticacion { get; set; }
        public string codigoAutenticacion { get; set; }
    }
}

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Models/Login.cs
namespace Doble_Autenticacion_NET.Models
{
    public class LoginUsuario
    {
        public string usuario { get; set; }
        public string contrasena { get; set; }
    }
}

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Controllers/AutenticadorController.cs
using Doble_Autenticacion_NET.Models;
using Google.Authenticator;
using System;
using System.Web.Mvc;

namespace Doble_Autenticacion_NET.Controllers
{
    public class AutenticadorController : Controller
    {
        public string nombreAplicacion = "Autenticacion Net";
        public string correoUsuario = "Prueba@gmail.com";
        public string claveAutenticador = "Prueba-Autenticacion-Net";

        // POST: Autenticador/Create
        [HttpPost]
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult GeneradorToken()
        {
            try
            {
                TwoFactorAuthenticator autenticador = new TwoFactorAuthenticator();

                string nombreAplicacion = "Autenticacion Net";
                string correoUsuario = "Prueba@gmail.com";
                string clave = "Prueba-Autenticacion-Net";

                SetupCode setupCode = autenticador.GenerateSetupCode(nombreAplicacion, correoUsuario, clave, false);

                ViewBag.ImagenQR = setupCode.QrCodeSetupImageUrl;
                ViewBag.CodigoManual = setupCode.ManualEntryKey;
            }
            catch (Exception ex)
            {
            }
            return View();
        }

        /// <summary>
        /// Valida la clave ingresada
        /// </summary>
        /// <param name="clave"></param>
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult ValidadorPing(string clave)
        {
            TwoFactorAuthenticator autenticador = new TwoFactorAuthenticator();

            bool pingCOrrecto = autenticador.ValidateTwoFactorPIN(claveAutenticador,clave);

            return Json(pingCOrrecto, JsonRequestBehavior.AllowGet);
        }
    }
}

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Controllers/HomeController.cs
using Doble_Autenticacion_NET.Models;
using System.Web.Mvc;

namespace Doble_Autenticacion_NET.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Views/Autenticador/GeneradorToken.cshtml
@{
    ViewBag.Title = "GeneradorToken";
}

<h2>Codigo Autenticacion</h2>

<h1>Paso 1: Registra tu dispositivo</h1>
<h2>Activar Autenticador de Google</h2>
<h3>Usa la cámara de tu celular</h3>
<img src="@ViewBag.ImagenQR" alt="QR" />

<h3>O Utiliza este código</h3>
@ViewBag.CodigoManual

<h1>Paso 2: Coloca la clave que indica Google Authenticator en estos momentos</h1>

@using (Html.BeginForm("ValidadorPing", "Autenticador", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <span>Clave:</span>
    <input type="text" id="Clave" name="clave" />

    <input type="button" value="Listo" class="btn btn-success" onclick="ValidarToken()"/>
    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" });
}

@Scripts.Render("~/bundles/Autenticacion")

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Views/Home/Index.cshtml
@model Doble_Autenticacion_NET.Models.LoginUsuario

@{
    ViewBag.Title = "Login";
}

<div class="container-fluid col-lg">
    <div class="form-bg center-block">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6">
                    <div class="form-container">
                        @using (Html.BeginForm("Login", "Autenticador", FormMethod.Post, new { @class= "form-horizontal" }))
                        {
                            <h3 class="title">Login </h3>
                            <div class="form-group">
                                <span class="input-icon"><i class="fa fa-user"></i></span>
                                @Html.TextBoxFor(model => model.usuario, new { @class = "form-control", @placeholder = "Usuario", @type = "email" })
                            </div>
                            <div class="form-group">
                                <span class="input-icon"><i class="fa fa-lock"></i></span>
                                @Html.PasswordFor(model => model.contrasena, new { @class="form-control", @placeholder = "Contraseña" })
                            </div>
                            <button class=" center-block btn signin">Log in</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Styles.Render("~/Content/Login")

Doble Autenticacion NET/Doble Autenticacion NET/Doble Autenticacion NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Autenticación Dos factores</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Doble Autenticación .Net 4.8", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Index", "Home")</li>
                    <li>@Html.ActionLink("Configuración de Google Autenticación", "GeneradorToken", "Autenticador")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Doble Autenticación .Net 4.8</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>